---
title: "Promoter_2nd.Rmd"
output: html_document
---

```{r, echo=F}
id <- c(1)
team_name <- c("BOKU-Vienna")
project <- c("help people dealing with sepsis caused by Lipopolysaccharides (LPS) from gram-negative bacteria lysis.")
                
year <- c(2020) 
                  
wiki <- c("https://2020.igem.org/Team:BOKU-Vienna")
 

igem_team <- data.frame(no, 
                        team_name, 
                        project, 
                        year, 
                        wiki)
#knitr::kable(igem_team)
igem_team
```
```{r, echo=F}
id <- 1:4
BBid <- c("BBa_J23101", 
          "BBa_J23105",
          "BBa_B1001",
          "BBa_J06504")
type <- c("Promoter",
          "Promoter",
          "Terminator",
          "Reporter mCherry")
link <- c("http://parts.igem.org/Part:BBa_J23101",
          "http://parts.igem.org/Part:BBa_J23105",
          "http://parts.igem.org/Part:BBa_B1001",
          "http://parts.igem.org/Part:BBa_J06504")
backbone <- rep("-", length(id))
device_id <- paste0("D", sprintf("%04d", rep(1, length(id))) )
team_name <- rep("BOKU-Vienna", length(id))
user <- rep("yoo-bh", length(id))

igem_part <- data.frame(id, BBid, type, link, backbone, device_id, team_name, user)
#knitr::kable(igem_part)
igem_part
           
```

```{r, echo=F}
id <- c(1:4)
promoter <- c("BBa_J23101", "BBa_J23101", "BBa_J23105", "BBa_J23105")
indc <- rep("Time", length(id))
Time <- c(5, 7, 5, 7)
value <- c(950, 1350, 10,20 )
valunit <- rep("Fluorescence", length(id))
incubhr <- rep("8", length(id))
incubtemp <- rep("-", length(id))
device_id <- rep("D0001", length(id))
link <- c("https://2020.igem.org/Team:BOKU-Vienna/Results",
          "https://2020.igem.org/Team:BOKU-Vienna/Results",
          "https://2020.igem.org/Team:BOKU-Vienna/Results",
          "https://2020.igem.org/Team:BOKU-Vienna/Results")
igem_obs <- data.frame(id, promoter, indc, Time, value,
                        valunit, incubhr, incubtemp,
                       device_id, link)
#knitr::kable(igem_obs)
igem_obs
```
```{r, echo=F}
library(tidyverse)

igem_promoter <- igem_part %>% 
  left_join(igem_team, by="team_name") %>% 
  left_join(igem_obs, by="device_id")
  
igem_promoter
```

```{r, echo=F}
colnames(igem_promoter)

plot_data <- igem_promoter %>% 
  filter(BBid=="BBa_J23101") %>% 
  select(promoter, Time, value) %>% 
  mutate(strain=factor(promoter), Time=factor(Time))

```
```{r, echo=F}
ggplot(plot_data, aes(x=promoter, y=value, fill=Time)) +
  geom_bar(stat="identity", position=position_dodge(width=0.5), width=0.4) +
  scale_fill_manual(values=c("#ce1212", "#4a47a3")) +
  theme_bw()
```



